plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git":
      assets:
        - package.json
        - package-lock.json
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
