name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install semantic-release
        run: npm install semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github --no-save

      - name: Run semantic-release
        run: npx semantic-release --no-ci --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
